In [1]:
import pandas as pd

In [2]:
dict_data = {
    "c0":[1,2,3], 
    "c1":[4,5,6], 
    "c2":[7,8,9], 
    "c3":[10,11,12], 
    "c4":[13,14,15]
    }

df = pd.DataFrame(dict_data)
print(type(df))
print(df)

<class 'pandas.DataFrame'>
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [7]:
# pandas.DataFrame(2차원배열,
#                  index=행 인덱스 배열,
#                  columns=열 이름 배열
#                  )

arr = [
    [15, "남", "덕영중"], 
    [17, "여", "수리중"]
]

df = pd.DataFrame(arr, index=["준서", "예은"], columns=["나이", "성별", "학교"])

print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [8]:
print(df.index)
print(df.columns)

Index(['준서', '예은'], dtype='str')
Index(['나이', '성별', '학교'], dtype='str')

In [9]:
# 행 인덱스 변경 : DataFrame 객체.index = 새로운 행 인덱스 배열
# 열 이름 변경 : DataFrame 객체.columns = 새로운 열 이름 배열

print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [10]:
df.index = ["학생1", "학생2"]
print(df)

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [11]:
df.columns = ["연령", "남녀", "소속"]
print(df)

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [ ]:
# 행 인덱스 변경 : DataFrame 객체.rename(index={기존 인덱스:새 인덱스})
# 열 인덱스 변경 : DataFrame 객체.rename(columns={기존 이름:새 이름})

In [13]:
import pandas as pd

matrix = [
    [15, "남", "덕영중"],
    [17, "여", "수리중"]
    ]

df = pd.DataFrame(matrix, index=["준서", "예은"], columns=["나이", "성별", "학교"])
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [ ]:
df = df.rename(columns ={
    "나이": "연령",
    "성별": "남녀",
    "학교": "소속"
})
print(df)

    연령 남녀   소속
준서  15  남  덕영중
예은  17  여  수리중

In [17]:
df = df.rename(index = {
    "준서": "학생1",
    "예은": "학생2"
})
print(df)

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [20]:
# 행 / 열 삭제
# 행 삭제 : DataFrame 객체.drop(행 인덱스 또는 배열, axis = 0 또는 axis = "index") / axix(=는 축으로 어딜 지정할지)
# 열 삭제 : DataFrame 객체.drop(열 이름 또는 배열, axis = 1 또는 axis = "columns")

import pandas as pd

exam_data = {
    "수학": [90, 80, 70],
    "영어": [98, 89, 95],
    "음악": [85, 95, 100],
    "체육": [100, 90, 90]
    }

df = pd.DataFrame(exam_data, index = ["서준", "우현", "인아"])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [22]:
df2 = df.copy()
df2 = df2.drop("우현")
df2

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [26]:
df3 = df.copy()
df3
df3 = df.drop(["우현", "인아"])
df3

    수학  영어  음악   체육
서준  90  98  85  100

In [27]:
df4 = df.copy()
df4 = df4.drop(["우현", "인아"], axis = "index")
df4

    수학  영어  음악   체육
서준  90  98  85  100

In [28]:
df5 = df.copy()
df5 = df5.drop(index =["우현"])
df5

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [29]:
import pandas as pd

exam_data = {
    "수학": [90, 80, 70],
    "영어": [98, 89, 95],
    "음악": [85, 95, 100],
    "체육": [100, 90, 90]
    }

df = pd.DataFrame(exam_data, index = ["서준", "우현", "인아"])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [34]:
df2 = df.copy()
df2 = df2.drop("수학", axis=1)
df2

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [ ]:
df3 = df.copy()
df3 = df3.drop(["영어", "음악"], axis = 1) # axis = 1 = axis = "columns"
df3

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [ ]:
df4 = df.copy()
df4 = df4.drop(["영어", "음악"], axis = "columns")
df4

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [38]:
df5=df.copy()
df5 = df5.drop(columns=["수학"])
df5

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [39]:
# 행 선택

import pandas as pd

exam_data = {
    "수학": [90, 80, 70],
    "영어": [98, 89, 95],
    "음악": [85, 95, 100],
    "체육": [100, 90, 90]
    }

df = pd.DataFrame(exam_data, index = ["서준", "우현", "인아"])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [43]:
label1 = df.loc["서준"]
print(label1)
print(type(label1))

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.Series'>

In [46]:
position1 = df.iloc[0]
print(position1)
print(type(position1))

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.Series'>

In [47]:
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [48]:
label2 = df.loc[["서준", "우현"]]
print(label2)
print(type(label2))

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90
<class 'pandas.DataFrame'>

In [ ]:
# 하나를 가지고 오지만 대괄호[]를 이용하여 인덱서 안에 리스트 형태로 가져오는 경우 DataFrame으로 가져온다
label3 = df.loc[["서준"]]
print(label3)
print(type(label3))

    수학  영어  음악   체육
서준  90  98  85  100
<class 'pandas.DataFrame'>

In [51]:
position2 = df.iloc[[0, 1]]
print(position2)
print(type(position2))

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90
<class 'pandas.DataFrame'>

In [52]:
label3 = df.loc["서준": "인아"]
print(label3)

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [53]:
position3 = df.iloc[0:2]
print(position3)

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [70]:
# 열 선택
# 열 1개 선택(시리즈 생성) : DataFrame 객체["열 이름"] or DataFrame 객체.열 이름

import pandas as pd

exam_data = {
    "이름": ["서준", "우현", "인아"],
    "수학": [90, 80, 70],
    "영어": [98, 89, 95],
    "음악": [85, 95, 100],
    "체육": [100, 90, 90]
    }

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [71]:
math1 = df["수학"]
print(math1)
print(type(math1))

0    90
1    80
2    70
Name: 수학, dtype: int64
<class 'pandas.Series'>

In [72]:
english = df.영어
print(english)
print(type(english))

0    98
1    89
2    95
Name: 영어, dtype: int64
<class 'pandas.Series'>

In [80]:
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [62]:
music_gym = df[["음악", "체육"]]
print(music_gym)
print(type(music_gym))

    음악   체육
0   85  100
1   95   90
2  100   90
<class 'pandas.DataFrame'>

In [79]:
df1 = df["수학"]
df1.shape

(3,)

In [74]:
df2 = df[["수학"]]
df2.shape

(3, 1)

In [77]:
#범위 슬라이싱 : DataFrame 객체.iloc[ 시작 인덱스 : 끝 인덱스 : 슬라이싱 간격]

df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [87]:
df.iloc[::2]

    수학  영어   음악   체육
이름
서준  90  98   85  100
인아  70  95  100   90

In [ ]:
# 원소 선택
# 인덱스 이름 : DataFrame 객체.loc[행 인덱스, 열 이름]
# 정수 위치 인덱스 : DataFrame 객체.iloc[행 번호, 열 번호]

In [92]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [93]:
print(df.loc["서준", "음악"])

85

In [94]:
a = df.loc["서준", "음악"]
df.iloc[0, 2]

np.int64(85)

In [95]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [96]:
df.loc["서준", ["음악", "체육"]]

음악     85
체육    100
Name: 서준, dtype: int64

In [97]:
df.iloc[0, [2, 3]]

음악     85
체육    100
Name: 서준, dtype: int64

In [98]:
df.loc["서준","음악":"체육"]

음악     85
체육    100
Name: 서준, dtype: int64

In [99]:
df.iloc[0, 2:]

음악     85
체육    100
Name: 서준, dtype: int64

In [100]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [102]:
df.loc[["서준", "우현"], ["음악", "체육"]]

    음악   체육
이름
서준  85  100
우현  95   90

In [103]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [105]:
df.iloc[[0, 1], [2, 3]]

    음악   체육
이름
서준  85  100
우현  95   90

In [106]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [108]:
df.loc["서준":"우현", "음악":"체육"]

    음악   체육
이름
서준  85  100
우현  95   90

In [110]:
df.iloc[0:2, 2:]

    음악   체육
이름
서준  85  100
우현  95   90

In [ ]:
# 열 추가 : DateFrame 객체["추가하려는 열 이름"] = 데이터 값

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [112]:
exam_data = {
    "이름": ["서준", "우현", "인아"],
    "수학": [90, 80, 70],
    "영어": [98, 89, 95],
    "음악": [85, 95, 100],
    "체육": [100, 90, 90]
    }

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [114]:
df["국어"] = 80
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  80
2  인아  70  95  100   90  80

In [115]:
df["미술"] = [80, 90, 100]
df

   이름  수학  영어   음악   체육  국어   미술
0  서준  90  98   85  100  80   80
1  우현  80  89   95   90  80   90
2  인아  70  95  100   90  80  100

In [116]:
# 행 추가 : DataFrame.loc["새로운 행 이름"] = 데이터 값 (or 배열)

exam_data = {
    "이름": ["서준", "우현", "인아"],
    "수학": [90, 80, 70],
    "영어": [98, 89, 95],
    "음악": [85, 95, 100],
    "체육": [100, 90, 90]
    }

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [ ]:
print(df.loc[0:2]) #끝 범위 까지 포함
print(df.iloc[0:2])#끝 범위를 포함하지 않음

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
   이름  수학  영어  음악   체육
0  서준  90  98  85  100
1  우현  80  89  95   90

In [120]:
df.loc[3] = 0
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0

In [121]:
df.loc[4] = ["동규", 90, 80, 70, 60]
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0
4  동규  90  80   70   60

In [122]:
df.loc["행5"] = df.loc[3]
df

    이름  수학  영어   음악   체육
0   서준  90  98   85  100
1   우현  80  89   95   90
2   인아  70  95  100   90
3    0   0   0    0    0
4   동규  90  80   70   60
행5   0   0   0    0    0

In [19]:
# 원소 값 변경
# DataFrame 객체의 일부분 또는 원소를 선택 = 새로운 값

import pandas as pd

exam_data = {
    "이름": ["서준", "우현", "인아"],
    "수학": [90, 80, 70],
    "영어": [98, 89, 95],
    "음악": [85, 95, 100],
    "체육": [100, 90, 90]
    }

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [20]:
df = df.set_index("이름")
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [21]:
df.iloc[0, 3] = 80
df

    수학  영어   음악  체육
이름
서준  90  98   85  80
우현  80  89   95  90
인아  70  95  100  90

In [22]:
df.loc["서준", "체육"] = 80

In [23]:
df

    수학  영어   음악  체육
이름
서준  90  98   85  80
우현  80  89   95  90
인아  70  95  100  90

In [24]:
df.loc[["서준"],["음악", "체육"]] = 50
df

    수학  영어   음악  체육
이름
서준  90  98   50  50
우현  80  89   95  90
인아  70  95  100  90

In [25]:
df.loc[["서준"],["음악", "체육"]] = 100, 50
df

    수학  영어   음악  체육
이름
서준  90  98  100  50
우현  80  89   95  90
인아  70  95  100  90

In [26]:
# 행과 열의 위치 바꾸기(많이 쓰임 / 행과 열의 축을 바꿈)
# 행, 열 바꾸기 : DataFrame 객체.transpose() or DataFrame 객체.T

import pandas as pd

exam_data = {
    "이름": ["서준", "우현", "인아"],
    "수학": [90, 80, 70],
    "영어": [98, 89, 95],
    "음악": [85, 95, 100],
    "체육": [100, 90, 90]
    }

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [27]:
df = df.transpose()
df

      0   1    2
이름   서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90

In [28]:
df = df.T
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90